
CREATE DATABASE UKACCIDENT;

USE UKACCIDENT;

CREATE TABLE ACCIDENTS(
    ACCIDENT_INDEX VARCHAR(100),
    LOCATION_EASTING_OSGR VARCHAR(100),
    LOCATION_NORTHING_OSGR VARCHAR(100),
    LONGITUDE DECIMAL(11,8),
    LATITUDE DECIMAL(10,8),
    POLICE_FORCE INT,
    ACCIDENT_SEVERITY INT,
    NUMBER_OF_VEHICLES INT,
    NUMBER_OF_CASUALTIES INT,
    DATE VARCHAR(100),
    DAY_OF_WEEK INT,
    TIME VARCHAR(100),
    LOCAL_AUTHORITY_DISTRICT VARCHAR(100),
    LOCAL_AUTHORITY_HIGHWAY VARCHAR(100),
    1ST_ROAD_CLASS VARCHAR(100),
    1ST_ROAD_NUMBER VARCHAR(100),
    ROAD_TYPE VARCHAR(100),
    SPEED_LIMIT INT,
    JUNCTION_DETAIL VARCHAR(100),
    JUNCTION_CONTROL VARCHAR(100),
    2ND_ROAD_CLASS VARCHAR(100),
    2ND_ROAD_NUMBER VARCHAR(100),
    PEDESTRIAN_CROSSING_HUMAN_CONTROL VARCHAR(100),
    PEDESTRIAN_CROSSING_PHYSICAL_FACILITIES VARCHAR(100),
    LIGHT_CONDITIONS VARCHAR(100),
    WEATHER_CONDITIONS VARCHAR(100),
    ROAD_SURFACE_CONDITIONS VARCHAR(100),
    SPECIAL_CONDITIONS_AT_SITE VARCHAR(100),
    CARRIAGEWAY_HAZARDS VARCHAR(100),
    URBAN_OR_RURAL_AREA VARCHAR(100),
    DID_POLICE_OFFICER_ATTEND_SCENE_OF_ACCIDENT VARCHAR(100),
    LSOA_OF_ACCIDENT_LOCATION VARCHAR(100),
    PRIMARY KEY (ACCIDENT_INDEX)
);

LOAD DATA INFILE
'D:/ACCIDENTS.csv'
INTO TABLE ACCIDENTS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM ACCIDENTS;


CREATE TABLE VEHICLE_TYPES(
    CODE VARCHAR(30),
    LABEL VARCHAR(100)
);

LOAD DATA INFILE
'D:/VEHICLE_TYPES.csv'
INTO TABLE VEHICLE_TYPES
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM VEHICLE_TYPES;


CREATE TABLE VEHICLES(
    ACCIDENT_INDEX VARCHAR(100),
    VEHICLE_REFERENCE VARCHAR(100),
    VEHICLE_TYPE VARCHAR(100),
    TOWING_AND_ARTICULATION VARCHAR(100),
    VEHICLE_MANOEUVRE VARCHAR(100),
    VEHICLE_LOCATION_RESTRICTED_LANE VARCHAR(100),
    JUNCTION_LOCATION VARCHAR(100),
    SKIDDING_AND_OVERTURNING VARCHAR(100),
    HIT_OBJECT_IN_CARRIAGEWAY VARCHAR(100),
    VEHICLE_LEAVING_CARRIAGEWAY VARCHAR(100),
    HIT_OBJECT_OFF_CARRIAGEWAY VARCHAR(100),
    1ST_POINT_OF_IMPACT VARCHAR(100),
    WAS_VEHICLE_LEFT_HAND_DRIVE VARCHAR(100),
    JOURNEY_PURPOSE_OF_DRIVER VARCHAR(100),
    SEX_OF_DRIVER VARCHAR(100),
    AGE_OF_DRIVER VARCHAR(100),
    AGE_BAND_OF_DRIVER VARCHAR(100),
    ENGINE_CAPACITY_CC VARCHAR(100),
    PROPULSION_CODE VARCHAR(100),
    AGE_OF_VEHICLE VARCHAR(100),
    DRIVER_IMD_DECILE VARCHAR(100),
    DRIVER_HOME_AREA_TYPE VARCHAR(100),
    VEHICLE_IMD_DECILE VARCHAR(100),
    PRIMARY KEY (ACCIDENT_INDEX, VEHICLE_REFERENCE)
);

LOAD DATA INFILE
'D:/VEHICLES.csv'
INTO TABLE VEHICLES
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM VEHICLES;


## Business Problem ##

/*The UK Department of Transport provides open datasets on road safety and casualties, and one can
use these datasets to analyze how safe the roads in the UK are.
This project will help you answer a few questions using their 2015 dataset.*/

# The dataset has 3 tables i.e Accident, vehicle, Vehicle_type #

## Approach/Project Idea ##

# Use aggregate functions in SQL and Python to answer the following sample questions. #

#1. Evaluate the median severity value of accidents caused by various Motorcycles.

WITH MOTORCYCLE_ACCIDENTS AS (
    SELECT DISTINCT
        VT.LABEL AS VEHICLE_TYPE,
        A.ACCIDENT_INDEX,
        A.ACCIDENT_SEVERITY
    FROM ACCIDENTS A
    JOIN VEHICLES V
        ON A.ACCIDENT_INDEX = V.ACCIDENT_INDEX
    JOIN VEHICLE_TYPES VT
        ON V.VEHICLE_TYPE = VT.CODE
    WHERE UPPER(VT.LABEL) LIKE '%MOTORCYCLE%'
),
RANKED_SEVERITY AS (
    SELECT
        VEHICLE_TYPE,
        ACCIDENT_SEVERITY,
        ROW_NUMBER() OVER (
            PARTITION BY VEHICLE_TYPE
            ORDER BY ACCIDENT_SEVERITY
        ) AS ROW_NUM,
        COUNT(*) OVER (
            PARTITION BY VEHICLE_TYPE
        ) AS TOTAL_ROWS
    FROM MOTORCYCLE_ACCIDENTS
)
SELECT
    VEHICLE_TYPE AS 'VEHICLE TYPE',
    AVG(ACCIDENT_SEVERITY) AS MEDIAN_SEVERITY
FROM RANKED_SEVERITY
WHERE ROW_NUM IN (
    FLOOR((TOTAL_ROWS + 1) / 2),
    FLOOR((TOTAL_ROWS + 2) / 2)
)
GROUP BY VEHICLE_TYPE
ORDER BY MEDIAN_SEVERITY;


#2. Evaluate Accident Severity and Total Accidents per Vehicle Type.

SELECT
    VT.LABEL AS 'VEHICLE TYPE',
    SUM(A.ACCIDENT_SEVERITY) AS 'TOTAL SEVERITY',
    COUNT(DISTINCT A.ACCIDENT_INDEX) AS 'TOTAL ACCIDENTS'
FROM ACCIDENTS A
JOIN (
    SELECT DISTINCT ACCIDENT_INDEX, VEHICLE_TYPE
    FROM VEHICLES
) V
    ON A.ACCIDENT_INDEX = V.ACCIDENT_INDEX
JOIN VEHICLE_TYPES VT
    ON V.VEHICLE_TYPE = VT.CODE
GROUP BY VT.CODE, VT.LABEL
ORDER BY COUNT(DISTINCT A.ACCIDENT_INDEX) DESC;


#3. Calculate the Average Severity by vehicle type.

SELECT
    VT.LABEL AS 'VEHICLE TYPE',
    AVG(A.ACCIDENT_SEVERITY) AS 'ACCIDENT SEVERITY'
FROM ACCIDENTS A
JOIN (
    SELECT DISTINCT ACCIDENT_INDEX, VEHICLE_TYPE
    FROM VEHICLES
) V
    ON A.ACCIDENT_INDEX = V.ACCIDENT_INDEX
JOIN VEHICLE_TYPES VT
    ON V.VEHICLE_TYPE = VT.CODE
GROUP BY VT.CODE, VT.LABEL
ORDER BY AVG(A.ACCIDENT_SEVERITY);


#4. Calculate the Average Severity and Total Accidents by Motorcycle.

SELECT
    VT.LABEL AS 'VEHICLE TYPE',
    AVG(A.ACCIDENT_SEVERITY) AS 'AVERAGE SEVERITY',
    COUNT(DISTINCT A.ACCIDENT_INDEX) AS 'NUMBER OF ACCIDENTS'
FROM ACCIDENTS A
JOIN (
    SELECT DISTINCT ACCIDENT_INDEX, VEHICLE_TYPE
    FROM VEHICLES
) V
    ON A.ACCIDENT_INDEX = V.ACCIDENT_INDEX
JOIN VEHICLE_TYPES VT
    ON V.VEHICLE_TYPE = VT.CODE
WHERE UPPER(VT.LABEL) LIKE '%MOTORCYCLE%'
GROUP BY VT.CODE, VT.LABEL
ORDER BY AVG(A.ACCIDENT_SEVERITY),
         COUNT(DISTINCT A.ACCIDENT_INDEX);
