CREATE DATABASE ZOMATO;

USE ZOMATO;

CREATE TABLE RESTAURANT (
    RESTAURANT_ID VARCHAR(100),
    RESTAURANT_NAME VARCHAR(100),
    COUNTRY_CODE VARCHAR(100),
    CITY VARCHAR(100),
    ADDRESS VARCHAR(255),
    LOCALITY VARCHAR(255),
    LOCALITY_VERBOSE VARCHAR(255),
    LONGITUDE VARCHAR(100),
    LATITUDE VARCHAR(100),
    CUISINES VARCHAR(255),
    CURRENCY VARCHAR(100),
    HAS_TABLE_BOOKING VARCHAR(100),
    HAS_ONLINE_DELIVERY VARCHAR(100),
    IS_DELIVERING_NOW VARCHAR(100),
    SWITCH_TO_ORDER_MENU VARCHAR(100),
    PRICE_RANGE VARCHAR(100),
    VOTES VARCHAR(100),
    AVERAGE_COST_FOR_TWO VARCHAR(100),
    RATING VARCHAR(100),
    DATEKEY_OPENING VARCHAR(100),
    CUISINES_1 VARCHAR(100),
    CUISINES_2 VARCHAR(100),
    CUISINES_3 VARCHAR(100),
    CUISINES_4 VARCHAR(100),
    CUISINES_5 VARCHAR(100),
    CUISINES_6 VARCHAR(100),
    CUISINES_7 VARCHAR(100),
    CUISINES_8 VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

LOAD DATA INFILE 'D:/Restaurant.csv'
INTO TABLE RESTAURANT
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

CREATE TABLE COUNTRY (
    COUNTRY_ID VARCHAR(100),
    COUNTRY_NAME VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

LOAD DATA INFILE 'D:/Country.csv'
INTO TABLE COUNTRY
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Inspect source date formats before conversion.
SELECT DISTINCT DATEKEY_OPENING
FROM RESTAURANT
LIMIT 20;

-- Convert the date only after confirming its source format.
-- Example below assumes YYYY_MM_DD.
-- If your CSV uses DD_MM_YYYY, use '%d_%m_%Y' instead.
ALTER TABLE RESTAURANT
ADD COLUMN OPENING_DATE DATE;

UPDATE RESTAURANT
SET OPENING_DATE = STR_TO_DATE(
    DATEKEY_OPENING, '%Y_%m_%d'
)
WHERE DATEKEY_OPENING REGEXP
'^[0-9]{4}_[0-9]{1,2}_[0-9]{1,2}$';

-- #1. Build a Calendar Table using the Column Datekey.
-- A. Year
-- B. Monthno
-- C. Monthfullname
-- D. Quarter (Q1,Q2,Q3,Q4)
-- E. YearMonth (YYYY-MMM)
-- F. Weekdayno
-- G. Weekdayname
-- H. FinancialMonth (April=FM1 ... March=FM12)
-- I. Financial Quarter

SELECT
    YEAR(OPENING_DATE) AS YEAR,
    MONTH(OPENING_DATE) AS MONTHNO,
    MONTHNAME(OPENING_DATE) AS MONTHFULLNAME,
    CONCAT('Q', QUARTER(OPENING_DATE)) AS QUARTER,
    DATE_FORMAT(OPENING_DATE, '%Y-%b') AS YEARMONTH,
    WEEKDAY(OPENING_DATE) + 1 AS WEEKDAYNO,
    DAYNAME(OPENING_DATE) AS WEEKDAYNAME,
    CONCAT(
        'FM',
        MOD(MONTH(OPENING_DATE) + 8, 12) + 1
    ) AS FINANCIAL_MONTH,
    CONCAT(
        'FQ',
        FLOOR(
            MOD(MONTH(OPENING_DATE) + 8, 12) / 3
        ) + 1
    ) AS FINANCIAL_QUARTER
FROM RESTAURANT
WHERE OPENING_DATE IS NOT NULL;

-- #2. Find the number of restaurants based on city and country.

SELECT
    C.COUNTRY_NAME,
    R.CITY,
    COUNT(DISTINCT R.RESTAURANT_ID) AS NO_OF_RESTAURANTS
FROM RESTAURANT R
JOIN COUNTRY C
    ON R.COUNTRY_CODE = C.COUNTRY_ID
GROUP BY C.COUNTRY_NAME, R.CITY
ORDER BY NO_OF_RESTAURANTS DESC;

-- #3. Numbers of Restaurants opening based on year,
-- quarter, month.

SELECT
    YEAR(OPENING_DATE) AS YEAR,
    QUARTER(OPENING_DATE) AS QUARTER,
    MONTH(OPENING_DATE) AS MONTHNO,
    MONTHNAME(OPENING_DATE) AS MONTHNAME,
    COUNT(DISTINCT RESTAURANT_ID) AS NO_OF_RESTAURANTS
FROM RESTAURANT
WHERE OPENING_DATE IS NOT NULL
GROUP BY
    YEAR(OPENING_DATE),
    QUARTER(OPENING_DATE),
    MONTH(OPENING_DATE),
    MONTHNAME(OPENING_DATE)
ORDER BY YEAR, MONTHNO;

-- #4. Count of restaurants based on average ratings.

SELECT
    CASE
        WHEN CAST(RATING AS DECIMAL(4,2)) <= 2
            THEN '0-2'
        WHEN CAST(RATING AS DECIMAL(4,2)) <= 3
            THEN '2-3'
        WHEN CAST(RATING AS DECIMAL(4,2)) <= 4
            THEN '3-4'
        WHEN CAST(RATING AS DECIMAL(4,2)) <= 5
            THEN '4-5'
        ELSE 'Unknown'
    END AS RATING_RANGE,
    COUNT(DISTINCT RESTAURANT_ID) AS RESTAURANT_COUNT
FROM RESTAURANT
WHERE RATING REGEXP '^[0-9]+([.][0-9]+)?$'
GROUP BY RATING_RANGE
ORDER BY RATING_RANGE;

-- #5. Create buckets based on average price
-- of reasonable size and find out how many
-- restaurants fall in each bucket.
-- Cost is in each restaurant's local currency.

SELECT
    CASE
        WHEN CAST(AVERAGE_COST_FOR_TWO AS DECIMAL(15,2)) <= 500
            THEN '0-500'
        WHEN CAST(AVERAGE_COST_FOR_TWO AS DECIMAL(15,2)) <= 3000
            THEN '500-3000'
        WHEN CAST(AVERAGE_COST_FOR_TWO AS DECIMAL(15,2)) <= 10000
            THEN '3000-10000'
        ELSE '>10000'
    END AS PRICE_BUCKET,
    COUNT(DISTINCT RESTAURANT_ID) AS RESTAURANT_COUNT
FROM RESTAURANT
WHERE AVERAGE_COST_FOR_TWO
    REGEXP '^[0-9]+([.][0-9]+)?$'
GROUP BY PRICE_BUCKET
ORDER BY
    CASE PRICE_BUCKET
        WHEN '0-500' THEN 1
        WHEN '500-3000' THEN 2
        WHEN '3000-10000' THEN 3
        ELSE 4
    END;

-- #6. Percentage of restaurants based on
-- "Has_Table_booking".

SELECT
    HAS_TABLE_BOOKING,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(
        COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM RESTAURANT),
        2
    ) AS PERCENTAGE
FROM RESTAURANT
GROUP BY HAS_TABLE_BOOKING;

-- #7. Percentage of restaurants based on
-- "Has_Online_delivery".

SELECT
    HAS_ONLINE_DELIVERY,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(
        COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM RESTAURANT),
        2
    ) AS PERCENTAGE
FROM RESTAURANT
GROUP BY HAS_ONLINE_DELIVERY;

-- HIGHEST RATING RESTAURANTS IN EACH COUNTRY

WITH RANKED_RESTAURANTS AS (
    SELECT
        C.COUNTRY_NAME,
        R.RESTAURANT_NAME,
        R.RESTAURANT_ID,
        CAST(R.RATING AS DECIMAL(4,2)) AS RATING,
        DENSE_RANK() OVER (
            PARTITION BY C.COUNTRY_ID
            ORDER BY CAST(R.RATING AS DECIMAL(4,2)) DESC
        ) AS RATING_RANK
    FROM RESTAURANT R
    JOIN COUNTRY C
        ON R.COUNTRY_CODE = C.COUNTRY_ID
    WHERE R.RATING REGEXP '^[0-9]+([.][0-9]+)?$'
)
SELECT
    COUNTRY_NAME,
    RESTAURANT_NAME,
    RATING AS HIGHEST_RATING
FROM RANKED_RESTAURANTS
WHERE RATING_RANK = 1
ORDER BY COUNTRY_NAME, RESTAURANT_NAME;

-- TOP 5 RESTAURANTS WHO HAS MORE NUMBER OF VOTES

SELECT
    C.COUNTRY_NAME,
    R.RESTAURANT_NAME,
    CAST(R.VOTES AS UNSIGNED) AS VOTES,
    R.AVERAGE_COST_FOR_TWO,
    R.CURRENCY
FROM RESTAURANT R
JOIN COUNTRY C
    ON R.COUNTRY_CODE = C.COUNTRY_ID
WHERE R.VOTES REGEXP '^[0-9]+$'
ORDER BY CAST(R.VOTES AS UNSIGNED) DESC
LIMIT 5;

-- TOP RESTAURANT WITH HIGHEST RATING AND VOTES
-- FROM EACH COUNTRY

WITH RANKED_RESTAURANTS AS (
    SELECT
        C.COUNTRY_NAME,
        R.RESTAURANT_NAME,
        CAST(R.RATING AS DECIMAL(4,2)) AS RATING,
        CAST(R.VOTES AS UNSIGNED) AS VOTES,
        ROW_NUMBER() OVER (
            PARTITION BY C.COUNTRY_ID
            ORDER BY
                CAST(R.RATING AS DECIMAL(4,2)) DESC,
                CAST(R.VOTES AS UNSIGNED) DESC,
                R.RESTAURANT_ID
        ) AS RN
    FROM RESTAURANT R
    JOIN COUNTRY C
        ON R.COUNTRY_CODE = C.COUNTRY_ID
    WHERE R.RATING REGEXP '^[0-9]+([.][0-9]+)?$'
      AND R.VOTES REGEXP '^[0-9]+$'
)
SELECT
    COUNTRY_NAME,
    RESTAURANT_NAME,
    RATING AS HIGHEST_RATING,
    VOTES
FROM RANKED_RESTAURANTS
WHERE RN = 1
ORDER BY RATING DESC, VOTES DESC
LIMIT 5;

-- CUISINE ANALYSIS

SELECT
    SUBSTRING_INDEX(CUISINES, ',', 1) AS SPLIT
FROM RESTAURANT;

SELECT
    RESTAURANT_NAME,
    CUISINES,
    TRIM(SUBSTRING_INDEX(CUISINES, ',', 1)) AS SPLIT,
    TRIM(SUBSTRING_INDEX(CUISINES, ',', 2)) AS FIRST_TWO_CUISINES,
    TRIM(SUBSTRING_INDEX(CUISINES, ',', 1)) AS FIRST_CUISINE
FROM RESTAURANT;

SELECT
    RESTAURANT_NAME,
    CUISINES,
    TRIM(SUBSTRING_INDEX(CUISINES, ',', 1)) AS CUISINE_1,
    CASE
        WHEN CUISINES LIKE '%,%'
        THEN TRIM(
            SUBSTRING_INDEX(
                SUBSTRING_INDEX(CUISINES, ',', 2), ',', -1
            )
        )
    END AS CUISINE_2,
    CASE
        WHEN CUISINES LIKE '%,%,%'
        THEN TRIM(
            SUBSTRING_INDEX(
                SUBSTRING_INDEX(CUISINES, ',', 3), ',', -1
            )
        )
    END AS CUISINE_3
FROM RESTAURANT;
